---
- name: Devops Grad Test
  hosts: grad-test-remote
  remote_user: vagrant
  sudo: yes

  tasks:
   - name: Ubuntu Server Old Version
     shell: lsb_release -d | awk '{print $2,$3,$4}'
     register: old_version

   - name: Print Old Version
     debug: var=old_version.stdout_lines

   - name: Update Package Lists
     apt: update_cache=yes

   - name: Packages To Upgrade
     shell: aptitude -q -F%p --disable-columns search "~U"
     register: updates
     changed_when: False

   - name: Print Packages To Upgrade
     debug: msg="{{ updates.stdout_lines | count }} packages to upgarde ({{ updates.stdout_lines | join(', ') }})"

   - name: Upgrade Packages
     apt: upgrade=safe

   - name: Ubuntu Server New Version
     shell: lsb_release -d | awk '{print $2,$3,$4}'
     register: new_version

   - name: Print New Version
     debug: msg="Ubuntu has been upgraded from {{ old_version.stdout }} to {{ new_version.stdout }}"

   - name: Packages To Restart
     shell: checkrestart | grep ^service | awk '{print $2}'
     register: package_restart
     changed_when: False

   - name: Print Packages To Restart
     debug: msg="{{package_restart.stdout_lines | count }} packages to restart ({{ package_restart.stdout_lines | join (', ') }})"

   #Todo - Reboot

   #Todo - Show Uptime


